name: deploy app to kubernetes cluster

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Install yc
      run: |
        curl -s https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
        echo "~/yandex-cloud/bin" >> $GITHUB_PATH
        source ~/.bashrc

    - name: Create kubeconfig
      run: yc managed-kubernetes cluster get-credentials crawler-cluster --external --cloud-id $YC_CLOUD_ID --token $YC_TOKEN
      env:
        YC_CLOUD_ID: ${{secrets.YC_CLOUD_ID}}
        YC_TOKEN: ${{secrets.YC_TOKEN}}


    - name: check
      shell: bash
      run: |
        kubectl version

